name: Argo Rollouts Fork CI 

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-pre:
    runs-on: [ medium ]
    permissions:
      id-token: write
      contents: read
    steps:
    
      - name: Checkout Application Repository
        uses: actions/checkout@v4

      - uses: actions/setup-go@v3
        with:
          go-version: '1.22'
          
      - name: Build application
        run: |
          go mod vendor
          GOOS=linux GOARCH=amd64 go build -v -o build/rollouts-controller-linux-amd64 ./cmd/rollouts-controller
        env:
          CGO_ENABLED: 0 
  
      - name: Set up Docker context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders
          
      - name: Build images
        id: buildimages
        run: |
          img=ghcr.io/${{github.repository}}:${{github.sha}}
          echo "IMAGE_NAME=${img}" >> ${GITHUB_OUTPUT}
          docker pull ${img} || (
            docker buildx build --push --cache-to type=gha,mode=max --cache-from type=gha --progress plain --platform linux/arm64/v8,linux/amd64 --build-arg BUILDKIT_INLINE_CACHE=1 -t ${img}  .
          )
          
